/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zw.org.nbsz.portal.web.controller.admin;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import zw.org.nbsz.business.domain.Donation;
import zw.org.nbsz.business.domain.DonationStats;
import zw.org.nbsz.business.domain.Offer;
import zw.org.nbsz.business.domain.Person;
import zw.org.nbsz.business.service.CentreService;
import zw.org.nbsz.business.service.CollectSiteService;
import zw.org.nbsz.business.service.DonationService;
import zw.org.nbsz.business.service.DonationStatsService;
import zw.org.nbsz.business.service.OfferService;
import zw.org.nbsz.business.service.PersonService;
import zw.org.nbsz.business.util.DateUtil;
import zw.org.nbsz.business.util.dto.SearchDTO;
import zw.org.nbsz.portal.util.TableEvent;
import zw.org.nbsz.report.api.service.PersonReportService;
import zw.org.nbsz.portal.web.controller.BaseController;

/**
 *
 * @author Tasunungurwa Muzinda
 */
@Controller
@RequestMapping("/admin/donor")
public class PersonController extends BaseController {

    @Resource
    PersonReportService personReportService;

    @Resource
    private CentreService centreService;

    @Resource
    private CollectSiteService collectSiteService;

    @Resource
    private PersonService personService;

    @Resource
    private DonationStatsService donationStatsService;

    @Resource
    private DonationService donationService;
    
    @Resource
    private OfferService offerService;

    public void setUpModel(ModelMap model, SearchDTO item) {
        model.addAttribute("pageTitle", appPrefix + "Donation Entry Report");
        model.addAttribute("item", item.getInstance(item));
        model.addAttribute("excelExport", "/report/aggregate/data-entry/export/excel" + item.getQueryString(item.getInstance(item)));
        model.addAttribute("centres", centreService.getAll());
        if (item.getCentre() != null) {
            model.addAttribute("collectSites", collectSiteService.getByCentre(item.getCentre()));
        }
    }

    @RequestMapping(value = "/donor-entry", method = RequestMethod.GET)
    public String getReportIndex(ModelMap model) {
        setUpModel(model, new SearchDTO());
        return "report/donationReport";
    }

    @RequestMapping(value = "/donor-entry", method = RequestMethod.POST)
    public String getReportResult(ModelMap model, @ModelAttribute("item") SearchDTO item) {
        setUpModel(model, item);
        //model.addAttribute("items", personService.get(item.getInstance(item)));
        model.addAttribute("items", offerService.get(item.getInstance(item)));
        return "report/donationReport";
    }

    /*@RequestMapping(value = "/data-entry/export/excel", method = RequestMethod.GET)
    public void getExcelExportHealthCenter(HttpServletResponse response, SearchDTO item) {
        String name = DateUtil.getFriendlyFileName("Data Report");
        forceDownLoad(officeExportService.exportExcelFile(dataEntryReportService.getDefaultReport(item.getInstance(item)), name), name, response);
    }*/
    @RequestMapping(value = "/form", method = RequestMethod.GET)
    public String createDonorFormPDF(HttpServletResponse response, HttpServletRequest request, @RequestParam("id") Long id) {
        //Person person = personService.get(id);
        Offer offer = offerService.get(id);
        Person person = offer.getPerson();
        Document document = new Document();
        Font labelFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD);
        Font headerFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
        Font generalFont = new Font(Font.FontFamily.HELVETICA, 10);
        try {
            response.setContentType("application/pdf");
            PdfWriter writer = PdfWriter.getInstance(document, response.getOutputStream());
            document.open();
            PdfPTable headerTable = new PdfPTable(3);
            headerTable.setWidthPercentage(100);
            headerTable.setSpacingBefore(10f);
            headerTable.setSpacingAfter(10f);
            headerTable.setWidths(new float[]{1f, 3f, 1f});
            PdfPCell cell1 = new PdfPCell();
            cell1.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell1.setBorder(Rectangle.NO_BORDER);
            headerTable.addCell(cell1);
            PdfPCell cell2 = new PdfPCell(new Paragraph("NATIONAL BLOOD SERVICE ZIMBABWE", headerFont));
            cell2.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell2.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell2.setBorder(Rectangle.NO_BORDER);
            headerTable.addCell(cell2);
            PdfPCell cell3 = new PdfPCell();
            cell3.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell3.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell3.setBorder(Rectangle.NO_BORDER);
            headerTable.addCell(cell3);
            document.add(headerTable);
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.setSpacingBefore(10f);
            table.setSpacingAfter(10f);
            float[] columnWidths = {1f, 1f, 1f, 1f};
            table.setWidths(columnWidths);
            table.setTableEvent(new TableEvent());
            PdfPCell donorNumberLabel = new PdfPCell(new Paragraph("Donor Number", labelFont));
            donorNumberLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            donorNumberLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            donorNumberLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(donorNumberLabel);
            PdfPCell donorNumber = new PdfPCell(new Paragraph(person.getDonorNumber(), generalFont));
            donorNumber.setHorizontalAlignment(Element.ALIGN_LEFT);
            donorNumber.setVerticalAlignment(Element.ALIGN_MIDDLE);
            donorNumber.setBorder(Rectangle.NO_BORDER);
            table.addCell(donorNumber);
            PdfPCell dueDateLabel = new PdfPCell(new Paragraph("Due Date", labelFont));
            dueDateLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            dueDateLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            dueDateLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(dueDateLabel);
            PdfPCell dueDate = new PdfPCell(new Paragraph(DateUtil.getStringFromDate(person.getEntryDate()), generalFont));
            dueDate.setHorizontalAlignment(Element.ALIGN_LEFT);
            dueDate.setVerticalAlignment(Element.ALIGN_MIDDLE);
            dueDate.setBorder(Rectangle.NO_BORDER);
            table.addCell(dueDate);
            PdfPCell nameLabel = new PdfPCell(new Paragraph("Name", labelFont));
            nameLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            nameLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            nameLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(nameLabel);
            PdfPCell name = new PdfPCell(new Paragraph(person.getFirstName() + " " + person.getSurname(), generalFont));
            name.setHorizontalAlignment(Element.ALIGN_LEFT);
            name.setVerticalAlignment(Element.ALIGN_MIDDLE);
            name.setBorder(Rectangle.NO_BORDER);
            table.addCell(name);
            PdfPCell titleLabel = new PdfPCell(new Paragraph("Title", labelFont));
            titleLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            titleLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            titleLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(titleLabel);
            PdfPCell title = new PdfPCell(new Paragraph("", generalFont));
            title.setHorizontalAlignment(Element.ALIGN_LEFT);
            title.setVerticalAlignment(Element.ALIGN_MIDDLE);
            title.setBorder(Rectangle.NO_BORDER);
            table.addCell(title);
            PdfPCell idLabel = new PdfPCell(new Paragraph("Civil ID", labelFont));
            idLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            idLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            idLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(idLabel);
            PdfPCell idNumber = new PdfPCell(new Paragraph(person.getIdNumber(), generalFont));
            idNumber.setHorizontalAlignment(Element.ALIGN_LEFT);
            idNumber.setVerticalAlignment(Element.ALIGN_MIDDLE);
            idNumber.setBorder(Rectangle.NO_BORDER);
            table.addCell(idNumber);
            PdfPCell dobLabel = new PdfPCell(new Paragraph("Date of birth", labelFont));
            dobLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            dobLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            dobLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(dobLabel);
            PdfPCell dob = new PdfPCell(new Paragraph(DateUtil.getStringFromDate(person.getDateOfBirth()), generalFont));
            dob.setHorizontalAlignment(Element.ALIGN_LEFT);
            dob.setVerticalAlignment(Element.ALIGN_MIDDLE);
            dob.setBorder(Rectangle.NO_BORDER);
            table.addCell(dob);
            PdfPCell classificationLabel = new PdfPCell(new Paragraph("Donor Clasification", labelFont));
            classificationLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            classificationLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            classificationLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(classificationLabel);
            PdfPCell classification = new PdfPCell(new Paragraph("", generalFont));
            classification.setHorizontalAlignment(Element.ALIGN_LEFT);
            classification.setVerticalAlignment(Element.ALIGN_MIDDLE);
            classification.setBorder(Rectangle.NO_BORDER);
            table.addCell(classification);
            PdfPCell numDonationsLabel = new PdfPCell(new Paragraph("Number of donations", labelFont));
            numDonationsLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            numDonationsLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            numDonationsLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(numDonationsLabel);
            PdfPCell numDonations = new PdfPCell(new Paragraph("", generalFont));
            numDonations.setHorizontalAlignment(Element.ALIGN_LEFT);
            numDonations.setVerticalAlignment(Element.ALIGN_MIDDLE);
            numDonations.setBorder(Rectangle.NO_BORDER);
            table.addCell(numDonations);
            PdfPCell occupationLabel = new PdfPCell(new Paragraph("Occupation", labelFont));
            occupationLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            occupationLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            occupationLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(occupationLabel);
            PdfPCell occupation = new PdfPCell(new Paragraph(person.getProfession() != null ? person.getProfession().getName() : "", generalFont));
            occupation.setHorizontalAlignment(Element.ALIGN_LEFT);
            occupation.setVerticalAlignment(Element.ALIGN_MIDDLE);
            occupation.setBorder(Rectangle.NO_BORDER);
            table.addCell(occupation);
            PdfPCell maritalStatusLabel = new PdfPCell(new Paragraph("Marital Status", labelFont));
            maritalStatusLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            maritalStatusLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            maritalStatusLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(maritalStatusLabel);
            PdfPCell maritalStatus = new PdfPCell(new Paragraph(person.getMaritalStatus() != null ? person.getMaritalStatus().getName() : "", generalFont));
            maritalStatus.setHorizontalAlignment(Element.ALIGN_LEFT);
            maritalStatus.setVerticalAlignment(Element.ALIGN_MIDDLE);
            maritalStatus.setBorder(Rectangle.NO_BORDER);
            table.addCell(maritalStatus);
            PdfPCell collectSiteLabel = new PdfPCell(new Paragraph("Collect Site", labelFont));
            collectSiteLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            collectSiteLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            collectSiteLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(collectSiteLabel);
            PdfPCell collectSite = new PdfPCell(new Paragraph(person.getCollectSite() != null ? person.getCollectSite().getName() : "", generalFont));
            collectSite.setHorizontalAlignment(Element.ALIGN_LEFT);
            collectSite.setVerticalAlignment(Element.ALIGN_MIDDLE);
            collectSite.setBorder(Rectangle.NO_BORDER);
            table.addCell(collectSite);
            PdfPCell emailLabel = new PdfPCell(new Paragraph("Email", labelFont));
            emailLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            emailLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            emailLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(emailLabel);
            PdfPCell email = new PdfPCell(new Paragraph(person.getEmail(), generalFont));
            email.setHorizontalAlignment(Element.ALIGN_LEFT);
            email.setVerticalAlignment(Element.ALIGN_MIDDLE);
            email.setBorder(Rectangle.NO_BORDER);
            table.addCell(email);
            PdfPCell addressLabel = new PdfPCell(new Paragraph("Address", labelFont));
            addressLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            addressLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            addressLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(addressLabel);
            PdfPCell address = new PdfPCell(new Paragraph(person.getResidentialAddress(), generalFont));
            address.setHorizontalAlignment(Element.ALIGN_LEFT);
            address.setVerticalAlignment(Element.ALIGN_MIDDLE);
            address.setBorder(Rectangle.NO_BORDER);
            table.addCell(address);
            PdfPCell phoneLabel = new PdfPCell(new Paragraph("Phone", labelFont));
            phoneLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            phoneLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            phoneLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(phoneLabel);
            PdfPCell phone = new PdfPCell(new Paragraph(person.getCellphoneNumber(), generalFont));
            phone.setHorizontalAlignment(Element.ALIGN_LEFT);
            phone.setVerticalAlignment(Element.ALIGN_MIDDLE);
            phone.setBorder(Rectangle.NO_BORDER);
            table.addCell(phone);
            PdfPCell cityLabel = new PdfPCell(new Paragraph("City/Town", labelFont));
            cityLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            cityLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cityLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(cityLabel);
            PdfPCell city = new PdfPCell(new Paragraph(person.getCity() != null ? person.getCity().getName() : "", generalFont));
            city.setHorizontalAlignment(Element.ALIGN_LEFT);
            city.setVerticalAlignment(Element.ALIGN_MIDDLE);
            city.setBorder(Rectangle.NO_BORDER);
            table.addCell(city);
            PdfPCell counsellorLabel = new PdfPCell(new Paragraph("Counsellor", labelFont));
            counsellorLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            counsellorLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            counsellorLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(counsellorLabel);
            PdfPCell counsellor = new PdfPCell(new Paragraph(person.getCounsellor() != null ? person.getCounsellor().getName() : "", generalFont));
            counsellor.setHorizontalAlignment(Element.ALIGN_LEFT);
            counsellor.setVerticalAlignment(Element.ALIGN_MIDDLE);
            counsellor.setBorder(Rectangle.NO_BORDER);
            table.addCell(counsellor);
            PdfPCell panelLabel = new PdfPCell(new Paragraph("Panel Name", labelFont));
            panelLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            panelLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            panelLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(panelLabel);
            PdfPCell panel = new PdfPCell(new Paragraph("", generalFont));
            panel.setHorizontalAlignment(Element.ALIGN_LEFT);
            panel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            panel.setBorder(Rectangle.NO_BORDER);
            table.addCell(panel);
            PdfPCell counsellorAddressLabel = new PdfPCell(new Paragraph("Counsellor Address", labelFont));
            counsellorAddressLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            counsellorAddressLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            counsellorAddressLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(counsellorAddressLabel);
            PdfPCell counsellorAddress = new PdfPCell(new Paragraph(person.getCounsellor() != null ? person.getCounsellor().getAddress() : "", generalFont));
            counsellorAddress.setHorizontalAlignment(Element.ALIGN_LEFT);
            counsellorAddress.setVerticalAlignment(Element.ALIGN_MIDDLE);
            counsellorAddress.setBorder(Rectangle.NO_BORDER);
            table.addCell(counsellorAddress);
            PdfPCell lastOfferLabel = new PdfPCell(new Paragraph("Last Blood Offer", labelFont));
            lastOfferLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            lastOfferLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            lastOfferLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(lastOfferLabel);
            PdfPCell lastOffer = new PdfPCell(new Paragraph("", generalFont));
            lastOffer.setHorizontalAlignment(Element.ALIGN_LEFT);
            lastOffer.setVerticalAlignment(Element.ALIGN_MIDDLE);
            lastOffer.setBorder(Rectangle.NO_BORDER);
            table.addCell(lastOffer);
            DonationStats stats = donationStatsService.getByPersonAndEntryDate(person, person.getEntryDate());
            PdfPCell weightLabel = new PdfPCell(new Paragraph("Weight", labelFont));
            weightLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            weightLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            weightLabel.setBorder(Rectangle.NO_BORDER);
            table.addCell(weightLabel);
            PdfPCell weight = new PdfPCell(new Paragraph(stats.getWeight() != null ? stats.getWeight() + "" : "", generalFont));
            weight.setHorizontalAlignment(Element.ALIGN_LEFT);
            weight.setVerticalAlignment(Element.ALIGN_MIDDLE);
            weight.setBorder(Rectangle.NO_BORDER);
            table.addCell(weight);
            document.add(table);
            PdfPTable healthTable = new PdfPTable(2);
            healthTable.setWidthPercentage(100);
            healthTable.setSpacingBefore(10f);
            healthTable.setSpacingAfter(10f);
            float[] colWidths = {3f, 1f};
            healthTable.setWidths(colWidths);
            healthTable.setTableEvent(new TableEvent());
            PdfPCell healthTableHeader = new PdfPCell(new Paragraph("SECTION B", labelFont));
            healthTableHeader.setHorizontalAlignment(Element.ALIGN_LEFT);
            healthTableHeader.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTableHeader.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(healthTableHeader);
            PdfPCell healthTableHeader1 = new PdfPCell();
            healthTableHeader1.setHorizontalAlignment(Element.ALIGN_LEFT);
            healthTableHeader1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTableHeader1.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(healthTableHeader1);
            PdfPCell feelingWellLabel = new PdfPCell(new Paragraph("Are you feeling well and have you been in good health in the last 6 weeks?", generalFont));
            feelingWellLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            feelingWellLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(feelingWellLabel);
            PdfPCell feelingWell = new PdfPCell(new Paragraph(stats.getFeelingWellToday() != null ? stats.getFeelingWellToday().getName() : "", generalFont));
            feelingWell.setHorizontalAlignment(Element.ALIGN_LEFT);
            feelingWell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(feelingWell);
            PdfPCell refusedToDonateLabel = new PdfPCell(new Paragraph("Have you ever been refused as a blood donor or told not to donate blood?", generalFont));
            refusedToDonateLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            refusedToDonateLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(refusedToDonateLabel);
            PdfPCell refusedToDonate = new PdfPCell(new Paragraph(stats.getRefusedToDonate() != null ? stats.getRefusedToDonate().getName() : "", generalFont));
            refusedToDonate.setHorizontalAlignment(Element.ALIGN_LEFT);
            refusedToDonate.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(refusedToDonate);
            PdfPCell contractedMalariaLabel = new PdfPCell(new Paragraph("Is there any possibility you might have contracted malaria in the past 3 months?", generalFont));
            contractedMalariaLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            contractedMalariaLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(contractedMalariaLabel);
            PdfPCell contractedMalaria = new PdfPCell(new Paragraph(stats.getBeenToMalariaArea() != null ? stats.getBeenToMalariaArea().getName() : "", generalFont));
            contractedMalaria.setHorizontalAlignment(Element.ALIGN_LEFT);
            contractedMalaria.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(contractedMalaria);
            PdfPCell takenFoodLabel = new PdfPCell(new Paragraph("Have you taken food in the last 2-4 hours?", generalFont));
            takenFoodLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            takenFoodLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(takenFoodLabel);
            PdfPCell takenFood = new PdfPCell(new Paragraph(stats.getMealOrSnack() != null ? stats.getMealOrSnack().getName() : "", generalFont));
            takenFood.setHorizontalAlignment(Element.ALIGN_LEFT);
            takenFood.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(takenFood);
            PdfPCell dangerousOccupationLabel = new PdfPCell(new Paragraph("Does your daily occupation or leisure pursuit involve an activity/occupation, which can lead to endangering you or anyone else should you become light-headed or faint as a result of donating blood?", generalFont));
            dangerousOccupationLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            dangerousOccupationLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(dangerousOccupationLabel);
            PdfPCell dangerousOccupation = new PdfPCell(new Paragraph(stats.getDangerousOccupation() != null ? stats.getDangerousOccupation().getName() : "", generalFont));
            dangerousOccupation.setHorizontalAlignment(Element.ALIGN_LEFT);
            dangerousOccupation.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(dangerousOccupation);
            PdfPCell label1 = new PdfPCell(new Paragraph("Do you or have you ever had:", labelFont));
            label1.setHorizontalAlignment(Element.ALIGN_LEFT);
            label1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label1.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label1);
            PdfPCell label2 = new PdfPCell(new Paragraph("", labelFont));
            label2.setHorizontalAlignment(Element.ALIGN_LEFT);
            label2.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label2.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label2);
            PdfPCell rheumaticFeverLabel = new PdfPCell(new Paragraph("Rheumatic fever, chest pains, heart disease or stroke?", generalFont));
            rheumaticFeverLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            rheumaticFeverLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(rheumaticFeverLabel);
            PdfPCell rheumaticFever = new PdfPCell(new Paragraph(stats.getRheumaticFever() != null ? stats.getRheumaticFever().getName() : "", generalFont));
            rheumaticFever.setHorizontalAlignment(Element.ALIGN_LEFT);
            rheumaticFever.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(rheumaticFever);
            PdfPCell lungDiseaseLabel = new PdfPCell(new Paragraph("Lung disease, tuberclosis or ashtma?", generalFont));
            lungDiseaseLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            lungDiseaseLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(lungDiseaseLabel);
            PdfPCell lungDisease = new PdfPCell(new Paragraph(stats.getLungDisease() != null ? stats.getLungDisease().getName() : "", generalFont));
            lungDisease.setHorizontalAlignment(Element.ALIGN_LEFT);
            lungDisease.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(lungDisease);
            PdfPCell cancerLabel = new PdfPCell(new Paragraph("Cancer, a blood disease, an abdominal bleeding disorder or a bleeding - gastric or duodenal ulcer?", generalFont));
            cancerLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            cancerLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(cancerLabel);
            PdfPCell cancer = new PdfPCell(new Paragraph(stats.getCancer() != null ? stats.getCancer().getName() : "", generalFont));
            cancer.setHorizontalAlignment(Element.ALIGN_LEFT);
            cancer.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(cancer);
            PdfPCell diabetesLabel = new PdfPCell(new Paragraph("Diabetes, thyroid disease, kidney disease, epilepsy(fits)?", generalFont));
            diabetesLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            diabetesLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(diabetesLabel);
            PdfPCell diabetes = new PdfPCell(new Paragraph(stats.getDiabetes() != null ? stats.getDiabetes().getName() : "", generalFont));
            diabetes.setHorizontalAlignment(Element.ALIGN_LEFT);
            diabetes.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(diabetes);
            PdfPCell chronicLabel = new PdfPCell(new Paragraph("Any other medical condition or relevant surgery?", generalFont));
            chronicLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            chronicLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(chronicLabel);
            PdfPCell chronic = new PdfPCell(new Paragraph(stats.getChronicMedicalCondition() != null ? stats.getChronicMedicalCondition().getName() : "", generalFont));
            chronic.setHorizontalAlignment(Element.ALIGN_LEFT);
            chronic.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(chronic);
            PdfPCell label3 = new PdfPCell(new Paragraph("In the past 7 days:", labelFont));
            label3.setHorizontalAlignment(Element.ALIGN_LEFT);
            label3.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label3.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label3);
            PdfPCell label4 = new PdfPCell(new Paragraph("", labelFont));
            label4.setHorizontalAlignment(Element.ALIGN_LEFT);
            label4.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label4.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label4);
            PdfPCell beenToDentistLabel = new PdfPCell(new Paragraph("Have you been to a dentist for anything other than a routine check/hygiene?", generalFont));
            beenToDentistLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            beenToDentistLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(beenToDentistLabel);
            PdfPCell beenToDentist = new PdfPCell(new Paragraph(stats.getBeenToDentist() != null ? stats.getBeenToDentist().getName() : "", generalFont));
            beenToDentist.setHorizontalAlignment(Element.ALIGN_LEFT);
            beenToDentist.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(beenToDentist);
            PdfPCell takenAntibioticsLabel = new PdfPCell(new Paragraph("Have you taken antibiotics, aspirin, anti-inflammatory medication or steroid drugs?", generalFont));
            takenAntibioticsLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            takenAntibioticsLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(takenAntibioticsLabel);
            PdfPCell takenAntibiotics = new PdfPCell(new Paragraph(stats.getTakenAntibiotics() != null ? stats.getTakenAntibiotics().getName() : "", generalFont));
            takenAntibiotics.setHorizontalAlignment(Element.ALIGN_LEFT);
            takenAntibiotics.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(takenAntibiotics);
            PdfPCell label5 = new PdfPCell(new Paragraph("In the past 4 months:", labelFont));
            label5.setHorizontalAlignment(Element.ALIGN_LEFT);
            label5.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label5.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label5);
            PdfPCell label6 = new PdfPCell(new Paragraph("", labelFont));
            label6.setHorizontalAlignment(Element.ALIGN_LEFT);
            label6.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label6.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label6);
            PdfPCell injectionLabel = new PdfPCell(new Paragraph("Have you had an injection, vaccination or inoculation?", generalFont));
            injectionLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            injectionLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(injectionLabel);
            PdfPCell injection = new PdfPCell(new Paragraph(stats.getInjection() != null ? stats.getInjection().getName() : "", generalFont));
            injection.setHorizontalAlignment(Element.ALIGN_LEFT);
            injection.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(injection);
            PdfPCell beenIllLabel = new PdfPCell(new Paragraph("Have you been ill or received treatment?", generalFont));
            beenIllLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            beenIllLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(beenIllLabel);
            PdfPCell beenIll = new PdfPCell(new Paragraph(stats.getBeenIll() != null ? stats.getBeenIll().getName() : "", generalFont));
            beenIll.setHorizontalAlignment(Element.ALIGN_LEFT);
            beenIll.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(beenIll);
            PdfPCell label7 = new PdfPCell(new Paragraph("In the past 6 months:", labelFont));
            label7.setHorizontalAlignment(Element.ALIGN_LEFT);
            label7.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label7.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label7);
            PdfPCell label8 = new PdfPCell(new Paragraph("", labelFont));
            label8.setHorizontalAlignment(Element.ALIGN_LEFT);
            label8.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label8.setBorder(Rectangle.NO_BORDER);
            healthTable.addCell(label8);
            PdfPCell transfusionLabel = new PdfPCell(new Paragraph("Have you or your sexual partner received a blood transfusion or been treated with human or animal blood products or clotting factor?", generalFont));
            transfusionLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            transfusionLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(transfusionLabel);
            PdfPCell transfusion = new PdfPCell(new Paragraph(stats.getReceivedBloodTransfusion() != null ? stats.getReceivedBloodTransfusion().getName() : "", generalFont));
            transfusion.setHorizontalAlignment(Element.ALIGN_LEFT);
            transfusion.setVerticalAlignment(Element.ALIGN_MIDDLE);
            healthTable.addCell(transfusion);
            if (person.getGender().equals("F")) {
                PdfPCell label9 = new PdfPCell(new Paragraph("Female Only", labelFont));
                label9.setHorizontalAlignment(Element.ALIGN_LEFT);
                label9.setVerticalAlignment(Element.ALIGN_MIDDLE);
                label9.setBorder(Rectangle.NO_BORDER);
                healthTable.addCell(label9);
                PdfPCell label10 = new PdfPCell(new Paragraph("", labelFont));
                label10.setHorizontalAlignment(Element.ALIGN_LEFT);
                label10.setVerticalAlignment(Element.ALIGN_MIDDLE);
                label10.setBorder(Rectangle.NO_BORDER);
                healthTable.addCell(label10);
                PdfPCell pregnantLabel = new PdfPCell(new Paragraph("Have you been pregnant in the past 9 months?", generalFont));
                pregnantLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
                pregnantLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
                healthTable.addCell(pregnantLabel);
                PdfPCell pregnant = new PdfPCell(new Paragraph(stats.getPregnant() != null ? stats.getPregnant().getName() : "", generalFont));
                pregnant.setHorizontalAlignment(Element.ALIGN_LEFT);
                pregnant.setVerticalAlignment(Element.ALIGN_MIDDLE);
                healthTable.addCell(pregnant);
                PdfPCell breastFeedingLabel = new PdfPCell(new Paragraph("Are you breastfeeding at the present time?", generalFont));
                breastFeedingLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
                breastFeedingLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
                healthTable.addCell(breastFeedingLabel);
                PdfPCell breastFeeding = new PdfPCell(new Paragraph(stats.getBreastFeeding() != null ? stats.getBreastFeeding().getName() : "", generalFont));
                breastFeeding.setHorizontalAlignment(Element.ALIGN_LEFT);
                breastFeeding.setVerticalAlignment(Element.ALIGN_MIDDLE);
                healthTable.addCell(breastFeeding);
            }
            document.add(healthTable);
            Donation item = donationService.findByPersonAndDonationDate(person, person.getEntryDate());
            PdfPTable riskTable = new PdfPTable(2);
            riskTable.setWidthPercentage(100);
            riskTable.setSpacingBefore(10f);
            riskTable.setSpacingAfter(10f);
            riskTable.setWidths(colWidths);
            riskTable.setTableEvent(new TableEvent());
            PdfPCell riskTableHeader = new PdfPCell(new Paragraph("SECTION B", labelFont));
            riskTableHeader.setHorizontalAlignment(Element.ALIGN_LEFT);
            riskTableHeader.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTableHeader.setBorder(Rectangle.NO_BORDER);
            riskTable.addCell(riskTableHeader);
            PdfPCell riskTableHeader1 = new PdfPCell();
            riskTableHeader1.setHorizontalAlignment(Element.ALIGN_LEFT);
            riskTableHeader1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTableHeader1.setBorder(Rectangle.NO_BORDER);
            riskTable.addCell(riskTableHeader1);
            PdfPCell reasonLabel = new PdfPCell(new Paragraph("Is your reason for donating blood to undergo a HIV test?", generalFont));
            reasonLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            reasonLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(reasonLabel);
            PdfPCell reason = new PdfPCell(new Paragraph(stats.getHivTest()!= null ? stats.getHivTest().getName() : "", generalFont));
            reason.setHorizontalAlignment(Element.ALIGN_LEFT);
            reason.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(reason);
            PdfPCell testedLabel = new PdfPCell(new Paragraph("Have you or your sexual partner ever tested positive for HIV, Hepatitis or Syphilis?", generalFont));
            testedLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            testedLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(testedLabel);
            PdfPCell tested = new PdfPCell(new Paragraph(stats.getBeenTestedForHiv()!= null ? stats.getBeenTestedForHiv().getName() : "", generalFont));
            tested.setHorizontalAlignment(Element.ALIGN_LEFT);
            tested.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(tested);
            PdfPCell illegalDrugsLabel = new PdfPCell(new Paragraph("Have you ever injected yourself or been injected with non-prescribed drugs?", generalFont));
            illegalDrugsLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            illegalDrugsLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(illegalDrugsLabel);
            PdfPCell illegalDrugs = new PdfPCell(new Paragraph(stats.getInjectedWithIllegalDrugs()!= null ? stats.getInjectedWithIllegalDrugs().getName() : "", generalFont));
            illegalDrugs.setHorizontalAlignment(Element.ALIGN_LEFT);
            illegalDrugs.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(illegalDrugs);
            PdfPCell prostitutionLabel = new PdfPCell(new Paragraph("Exchanged money, drugs,  goods or favours in return for sex?", generalFont));
            prostitutionLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            prostitutionLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(prostitutionLabel);
            PdfPCell prostitution = new PdfPCell(new Paragraph(stats.getExchangedMoneyForSex()!= null ? stats.getExchangedMoneyForSex().getName() : "", generalFont));
            prostitution.setHorizontalAlignment(Element.ALIGN_LEFT);
            prostitution.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(prostitution);
            PdfPCell stdLabel = new PdfPCell(new Paragraph("Have you or your sexual partner at an time since 2007 suffered from a sexually transmitted disease?", generalFont));
            stdLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            stdLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(stdLabel);
            PdfPCell std = new PdfPCell(new Paragraph(stats.getSufferedFromSTD()!= null ? stats.getSufferedFromSTD().getName() : "", generalFont));
            std.setHorizontalAlignment(Element.ALIGN_LEFT);
            std.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(std);
            PdfPCell jaundiceLabel = new PdfPCell(new Paragraph("Have you ever had Hepatitis (yellow jaundice) or been in contact with someone suffering from the disease in the past year?", generalFont));
            jaundiceLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            jaundiceLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(jaundiceLabel);
            PdfPCell jaundice = new PdfPCell(new Paragraph(stats.getContactWithPersonWithYellowJaundice()!= null ? stats.getContactWithPersonWithYellowJaundice().getName() : "", generalFont));
            jaundice.setHorizontalAlignment(Element.ALIGN_LEFT);
            jaundice.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(jaundice);
            PdfPCell trueForPartnerLabel = new PdfPCell(new Paragraph("Would your sexual partner/spouse answer yes to any of the above questions?", generalFont));
            trueForPartnerLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            trueForPartnerLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(trueForPartnerLabel);
            PdfPCell trueForPartner = new PdfPCell(new Paragraph(stats.getTrueForSexPartner()!= null ? stats.getTrueForSexPartner().getName() : "", generalFont));
            trueForPartner.setHorizontalAlignment(Element.ALIGN_LEFT);
            trueForPartner.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(trueForPartner);
            riskTable.addCell(label7);
            riskTable.addCell(label8);
            PdfPCell exposureLabel = new PdfPCell(new Paragraph("Have you had an accidental exposure to blood or body fluids e.g. (needle stick injury) or have been a victim of assault e.g. stabbing?", generalFont));
            exposureLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            exposureLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(exposureLabel);
            PdfPCell exposure = new PdfPCell(new Paragraph(stats.getAccidentalExposureToBlood()!= null ? stats.getAccidentalExposureToBlood().getName() : "", generalFont));
            exposure.setHorizontalAlignment(Element.ALIGN_LEFT);
            exposure.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(exposure);
            PdfPCell tattooedLabel = new PdfPCell(new Paragraph("Have you been tattooed, had an ear or body piercing, acupuncture or circumcision(from anyone other than a registered nurse or doctor), or scarification?", generalFont));
            tattooedLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            tattooedLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(tattooedLabel);
            PdfPCell tattooed = new PdfPCell(new Paragraph(stats.getBeenTattooedOrPierced()!= null ? stats.getBeenTattooedOrPierced().getName() : "", generalFont));
            tattooed.setHorizontalAlignment(Element.ALIGN_LEFT);
            tattooed.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(tattooed);
            PdfPCell abuseLabel = new PdfPCell(new Paragraph("Have you been a victim of sexual abuse e.g rape or sodomy?", generalFont));
            abuseLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            abuseLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(abuseLabel);
            PdfPCell abuse = new PdfPCell(new Paragraph(stats.getVictimOfSexualAbuse()!= null ? stats.getVictimOfSexualAbuse().getName() : "", generalFont));
            abuse.setHorizontalAlignment(Element.ALIGN_LEFT);
            abuse.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(abuse);
            PdfPCell label11 = new PdfPCell(new Paragraph("In the past 12 months:", labelFont));
            label11.setHorizontalAlignment(Element.ALIGN_LEFT);
            label11.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label11.setBorder(Rectangle.NO_BORDER);
            riskTable.addCell(label11);
            PdfPCell label12 = new PdfPCell(new Paragraph("", labelFont));
            label12.setHorizontalAlignment(Element.ALIGN_LEFT);
            label12.setVerticalAlignment(Element.ALIGN_MIDDLE);
            label12.setBorder(Rectangle.NO_BORDER);
            riskTable.addCell(label12);
            PdfPCell monogamyLabel = new PdfPCell(new Paragraph("Have you been in contact with someone suffering from HepatitisB?", generalFont));
            monogamyLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            monogamyLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(monogamyLabel);
            PdfPCell monogamy = new PdfPCell(new Paragraph(stats.getContactWithPersonWithHepatitisB()!= null ? stats.getContactWithPersonWithHepatitisB().getName() : "", generalFont));
            monogamy.setHorizontalAlignment(Element.ALIGN_LEFT);
            monogamy.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(monogamy);
            PdfPCell nightSweatsLabel = new PdfPCell(new Paragraph("Have you or your sexual partner suffered from night sweats, unintentional weight loss, diarrhoea or swollen glands?", generalFont));
            nightSweatsLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            nightSweatsLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(nightSweatsLabel);
            PdfPCell nightSweats = new PdfPCell(new Paragraph(stats.getSufferedFromNightSweats()!= null ? stats.getSufferedFromNightSweats().getName() : "", generalFont));
            nightSweats.setHorizontalAlignment(Element.ALIGN_LEFT);
            nightSweats.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(nightSweats);
            PdfPCell casualSexLabel = new PdfPCell(new Paragraph("Have you had casual sex with someone whose background you do not know?", generalFont));
            casualSexLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            casualSexLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(casualSexLabel);
            PdfPCell casualSex = new PdfPCell(new Paragraph(stats.getSexWithSomeoneWithUnknownBackground()!= null ? stats.getSexWithSomeoneWithUnknownBackground().getName() : "", generalFont));
            casualSex.setHorizontalAlignment(Element.ALIGN_LEFT);
            casualSex.setVerticalAlignment(Element.ALIGN_MIDDLE);
            riskTable.addCell(casualSex);
            document.add(riskTable);
            PdfPTable donationTable = new PdfPTable(4);
            donationTable.setWidthPercentage(100);
            donationTable.setSpacingBefore(10f);
            donationTable.setSpacingAfter(10f);
            float[] widths = {1f, 1f, 1f, 1f};
            donationTable.setWidths(widths);
            donationTable.setTableEvent(new TableEvent());
            PdfPCell weightLabel1 = new PdfPCell(new Paragraph("Weight", labelFont));
            weightLabel1.setHorizontalAlignment(Element.ALIGN_LEFT);
            weightLabel1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            weightLabel1.setBorder(Rectangle.NO_BORDER);
            donationTable.addCell(weightLabel1);
            PdfPCell weight1 = new PdfPCell(new Paragraph(stats.getWeight() != null ? stats.getWeight() + "" : "", generalFont));
            weight1.setHorizontalAlignment(Element.ALIGN_LEFT);
            weight1.setVerticalAlignment(Element.ALIGN_MIDDLE);
            weight1.setBorder(Rectangle.NO_BORDER);
            donationTable.addCell(weight1);
            PdfPCell bloodPressureLabel = new PdfPCell(new Paragraph("Blood Pressure", labelFont));
            bloodPressureLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
            bloodPressureLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
            bloodPressureLabel.setBorder(Rectangle.NO_BORDER);
            donationTable.addCell(bloodPressureLabel);
            PdfPCell bloodPressure = new PdfPCell(new Paragraph(stats.getBloodPressure(), generalFont));
            bloodPressure.setHorizontalAlignment(Element.ALIGN_LEFT);
            bloodPressure.setVerticalAlignment(Element.ALIGN_MIDDLE);
            bloodPressure.setBorder(Rectangle.NO_BORDER);
            donationTable.addCell(bloodPressure);
            if (item != null) {
                PdfPCell donationNumberLabel = new PdfPCell(new Paragraph("Donation Number", labelFont));
                donationNumberLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
                donationNumberLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
                donationNumberLabel.setBorder(Rectangle.NO_BORDER);
                donationTable.addCell(donationNumberLabel);
                PdfPCell donationNumber = new PdfPCell(new Paragraph(item.getDonationNumber(), generalFont));
                donationNumber.setHorizontalAlignment(Element.ALIGN_LEFT);
                donationNumber.setVerticalAlignment(Element.ALIGN_MIDDLE);
                donationNumber.setBorder(Rectangle.NO_BORDER);
                donationTable.addCell(donationNumber);
                PdfPCell bledByLabel = new PdfPCell(new Paragraph("Bled By", labelFont));
                bledByLabel.setHorizontalAlignment(Element.ALIGN_LEFT);
                bledByLabel.setVerticalAlignment(Element.ALIGN_MIDDLE);
                bledByLabel.setBorder(Rectangle.NO_BORDER);
                donationTable.addCell(bledByLabel);
                PdfPCell bledBy = new PdfPCell(new Paragraph(person.getBledBy() != null ? person.getBledBy().getName() : "", generalFont));
                bledBy.setHorizontalAlignment(Element.ALIGN_LEFT);
                bledBy.setVerticalAlignment(Element.ALIGN_MIDDLE);
                bledBy.setBorder(Rectangle.NO_BORDER);
                donationTable.addCell(bledBy);
            }
            document.add(donationTable);
            document.close();
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return "";
    }

}
